import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "./utils/cn";
import Header from "./components/Header";
import ConfigureAmplifyClientSide from "./components/ConfigureAmplify";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          "antialiased",
          "flex flex-col min-h-screen items-center text-white bg-black"
        )}
      >
        <ConfigureAmplifyClientSide />
        <Header />
        <main className="flex-grow">{children}</main>
        <footer>TODO</footer>
      </body>
    </html>
  );
}
